name: Org Policies

on:
  push:
    branches: [main, workflow_call_test]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '35 17 * * 0'

jobs:
  run-jobs:
    name: Org Policy Check
    uses: GenapsysInc/internal-actions/.github/workflows/org-policies.yml@main
    secrets:
      token: ${{ secrets.GH_REST_API_TOKEN }}
